# Site settings
title: "Megan Wallace"
description: "A community leader dedicated to furthering public access to top quality higher education in McKinney, Texas."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "Megan Wallace"
resume_title: "Trustee, Collin College"

# used for the contact button in _layouts/resume.html
resume_contact_email: "wallace.megan.c@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "972-836-6171"
resume_contact_address: "6400 Orchard Park Dr. McKinney, TX 75071"

resume_header_contact_info: "6400 Orchard Park Dr. McKinney, TX 75071 • 972-836-6171 • wallace.megan.c@gmail.com"
display_header_contact_info: "false"

resume_header_intro: "<p>Megan Wallace is a highly motivated and committed aspiring paralegal with a strong focus on e-discovery processes in litigation. Currently pursuing paralegal certification and developing skills in data analysis and computer forensics, she is well-equipped to excel in a legal environment that demands technological expertise. Megan is also an influential community leader in McKinney, Texas, dedicated to promoting public access to exceptional higher education opportunities.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
# resume_section_skills: true
# resume_section_recognition: true
resume_section_links: true
resume_section_certifications: true
resume_section_associations: true
resume_section_community: true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url: "https://github.com/jglovier/resume-template"
  # resume_twitter_url: "http://twitter.com/jglovier"
  # resume_dribbble_url: "https://dribbble.com/jag"
  resume_facebook_url: "https://www.facebook.com/meganwallacecollincounty"
  resume_linkedin_url: "https://www.linkedin.com/in/wallacemeganc"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url: "http://meganwallacecollincollegeboard.com"
  # resume_medium_url: "https://medium.com/@jglovier"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
